// Generated by CoffeeScript 1.10.0
(function() {
  var app, routes;

  app = require('./app').app;

  routes = require('./routes/web');

  require('./routes/socket');

  app.get('/', routes.index);

}).call(this);
